---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: local-dir-csidriver-plugin
  labels:
    "app.kubernetes.io/name": local-dir-csidriver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.local-dir-csidriver
    "app.kubernetes.io/part-of": local-dir-csidriver
    "app.kubernetes.io/component": plugin
spec:
  serviceName: local-dir-csidriver-plugin
  replicas: 1
  selector:
    matchLabels:
      "app.kubernetes.io/name": local-dir-csidriver-plugin
      "app.kubernetes.io/instance": io.github.leryn.csi.local-dir-csidriver
      "app.kubernetes.io/part-of": local-dir-csidriver
      "app.kubernetes.io/component": plugin
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": local-dir-csidriver-plugin
        "app.kubernetes.io/instance": io.github.leryn.csi.local-dir-csidriver
        "app.kubernetes.io/part-of": local-dir-csidriver
        "app.kubernetes.io/component": plugin
    spec:
      serviceAccountName: csi-local-dir-csidriver-sa
      containers:
        - name: csi-plugin
          image: harbor.leryn.top/infra/local-dir-csidriver-plugin:0.1.0
          imagePullPolicy: Always
          args:
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBERNETES_NODE_NAME)"
            - "--drivername=io.github.leryn.csi.local-dir-csidriver"
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          securityContext:
            privileged: true
          volumeMounts:
            - name: csi-socket-dir
              mountPath: /csi
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
            - name: plugins-dir
              mountPath: /var/lib/kubelet/plugins
              mountPropagation: Bidirectional
            - name: fuse-device
              mountPath: /dev/fuse

        - name: csi-external-health-monitor-controller
          image: registry.cn-hangzhou.aliyuncs.com/google_containers/csi-external-health-monitor-controller:v0.10.0
          imagePullPolicy: "IfNotPresent"
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: csi-socket-dir
              mountPath: /csi

        - name: livenessprobe
          image: registry.cn-hangzhou.aliyuncs.com/google_containers/livenessprobe:v2.11.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--health-port=9898"
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
          ports:
            - name: healthz
              containerPort: 9898
              protocol: TCP
          livenessProbe:
            httpGet:
              port: healthz
              path: /healthz
            initialDelaySeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
            periodSeconds: 2
          readinessProbe:
            httpGet:
              port: healthz
              path: /healthz
            initialDelaySeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
            periodSeconds: 2
          volumeMounts:
            - name: csi-socket-dir
              mountPath: /csi
              
        - name: csi-attacher
          image: registry.cn-hangzhou.aliyuncs.com/google_containers/csi-attacher:v4.4.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
          securityContext:
            privileged: true
          volumeMounts:
            - name: csi-socket-dir
              mountPath: /csi

        - name: csi-provisioner
          image: registry.cn-hangzhou.aliyuncs.com/google_containers/csi-provisioner:v3.6.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--feature-gates=Topology=true"
            - "--extra-create-metadata"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
              drop:
                - ALL
            privileged: true
          volumeMounts:
            - name: csi-socket-dir
              mountPath: /csi

      volumes:
        - name: csi-socket-dir
          emptyDir: {}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: local-dir-csidriver-plugin
  labels:
    "app.kubernetes.io/name": local-dir-csidriver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.local-dir-csidriver
    "app.kubernetes.io/part-of": local-dir-csidriver
    "app.kubernetes.io/component": csi-node-plugin
spec:
  selector:
    matchLabels:
      "app.kubernetes.io/name": local-dir-csidriver-plugin
      "app.kubernetes.io/instance": io.github.leryn.csi.local-dir-csidriver
      "app.kubernetes.io/part-of": local-dir-csidriver
      "app.kubernetes.io/component": csi-node-plugin
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": local-dir-csidriver-plugin
        "app.kubernetes.io/instance": io.github.leryn.csi.local-dir-csidriver
        "app.kubernetes.io/part-of": local-dir-csidriver
        "app.kubernetes.io/component": csi-node-plugin
    spec:
      serviceAccountName: csi-s3driver-sa
      containers:
        - name: csi-node-plugin
          image: harbor.leryn.top/infra/csi-s3driver:0.1.0
          imagePullPolicy: Always
          args:
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBERNETES_NODE_NAME)"
            - "--drivername=io.github.leryn.csi.local-dir-csidriver"
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
              drop:
                - ALL
            privileged: true
          volumeMounts:
            - name: csi-socket-dir
              mountPath: /csi
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
            - name: plugins-dir
              mountPath: /var/lib/kubelet/plugins
              mountPropagation: Bidirectional
            - name: fuse-device
              mountPath: /dev/fuse

        - name: csi-node-driver-registrar
          image: registry.cn-hangzhou.aliyuncs.com/google_containers/csi-node-driver-registrar:v2.9.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/io.github.leryn.csi.local-dir-csidriver/csi.sock"
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
          securityContext:
            privileged: true
          volumeMounts:
            - name: csi-socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration

        - name: livenessprobe
          image: registry.cn-hangzhou.aliyuncs.com/google_containers/livenessprobe:v2.11.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--health-port=9898"
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
          ports:
            - name: healthz
              containerPort: 9898
              protocol: TCP
          livenessProbe:
            httpGet:
              port: healthz
              path: /healthz
            initialDelaySeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
            periodSeconds: 2
          readinessProbe:
            httpGet:
              port: healthz
              path: /healthz
            initialDelaySeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
            periodSeconds: 2
          volumeMounts:
            - name: csi-socket-dir
              mountPath: /csi
      volumes:
        - name: csi-socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/io.github.leryn.csi.local-dir-csidriver
            type: DirectoryOrCreate
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: plugins-dir
          hostPath:
            path: /var/lib/kubelet/plugins
            type: Directory
        - name: fuse-device
          hostPath:
            path: /dev/fuse
