---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: io.github.leryn.csi.local-dir-csidriver
  labels:
    "app.kubernetes.io/name": local-dir-csidriver-plugin
    "app.kubernetes.io/instance": io.github.leryn.csi.local-dir-csidriver
    "app.kubernetes.io/part-of": local-dir-csidriver
    "app.kubernetes.io/component": csidriver
spec:
  attachRequired: true
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
